### ISSUE TITLE
IOException when app uses 3rd party SDK

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#422] opened 2020-08-13 08:50 UTC
## :writing_hand: Describe the bug
This issue arises from #394 

After fixes for #394 the reporter [provided update](https://github.com/ChuckerTeam/chucker/issues/394#issuecomment-671868443) that another exception appeared:

> ```
>  java.io.IOException: No such file or directory
>         at java.io.UnixFileSystem.createFileExclusively0(Native Method)
>         at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
>         at java.io.File.createNewFile(File.java:1008)
>         at com.chuckerteam.chucker.internal.support.AndroidCacheFileFactory.create(AndroidCacheFileFactory.kt:21)
>         at com.chuckerteam.chucker.internal.support.AndroidCacheFileFactory.create(AndroidCacheFileFactory.kt:15)
>         at com.chuckerteam.chucker.api.ChuckerInterceptor.multiCastResponseBody(ChuckerInterceptor.kt:184)
>         at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:92)
> ```
> It happens even after removing the application from device and reinstalling a new one.

## :wrench: Expected behavior
Chucker works normally and shows transactions.

## :iphone: Tech info
 - Chucker version: 3.3.0-SNAPSHOT (as of 11th of August 2020)

## :page_facing_up: Additional context
We should investigate the issue to either fix it or to get all the info we might need to deal with possible problems with other 3rd party SDKs.

**Comment by vbuberen** [comment] 2020-08-13 08:57
@CodeBreak524 Could you provide us with some more info? What request occurs at the point where you see this exception?
Since the SDK mentioned in your issue is closed one we need some bread crumbs to try and understand what happens there.

**Comment by koral--** [comment] 2020-08-13 09:08
From what I can see this issue can be easily reproduced. Just delete the cache directory when app is running.
No matter what is the exact reason the solution is to make sure that parent directory exists before calling `File#createNewFile()`.
It can be done by just calling `parentFile.mkdirs()` before this line: https://github.com/ChuckerTeam/chucker/blob/392a63b8043f3c967558a49bf84db481870537a2/library/src/main/java/com/chuckerteam/chucker/internal/support/AndroidCacheFileFactory.kt#L21
or by invoking `Context#getCacheDir()` on each file creation, not only at the init time: https://github.com/ChuckerTeam/chucker/blob/392a63b8043f3c967558a49bf84db481870537a2/library/src/main/java/com/chuckerteam/chucker/internal/support/AndroidCacheFileFactory.kt#L12
Note that cacheDir may be null which is also unhandled by Chucker and reported in #414.

**Comment by CodeBreak524** [comment] 2020-08-13 10:29
It seems that behaviour described above by @koral-- is the same for my case. 

It always happens after giving control to [IdNow SDK](https://github.com/idnow/de.idnow.android) and it looks like it removes all cache files and directories of app while processing. Of course it is not correct behaviour in IdNow but I also suppose that Chucker should handle such cases without throwing an error for request

**Comment by MiSikora** [comment] 2020-08-13 11:33
I'm not sure if this can be reproduced this way. We have a tests with that should cover that I think and it resulted in an error reported in #394. Unless this does not reproduce that or JVM behaves differently than Android when it comes to exceptions.

https://github.com/ChuckerTeam/chucker/blob/6820473cd15ab10f01f8dc3efd931555af3c9674/library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorTest.kt#L284-L316

**Comment by koral--** [comment] 2020-08-13 14:54
I've added a test demonstrating this scenario.

**Comment by MiSikora** [comment] 2020-08-13 15:31
Ok, so the fix would be to return `File?` from `FileFactory` and handle IO and possible NPE.

From the design perspective, it might be good to open the possibility of passing the temp files directory in the constructor? This way users could provide more reliable directory from their perspective. The issue I see is that it would make usage of files explicit, which would require major version bump to remove from the constructor. Also, file usage might be too new to stick to it. @vbuberen @cortinico what do you think?

**Comment by koral--** [comment] 2020-08-14 19:06
I'm not sure if that is not an overengineering.

IMHO the sufficient fix for this issue is to not save `context.getCacheDir()` result in a property but invoke it each time just before attempt to create the file. This should solve the vast majority of issues related to this ticket (`getCacheDir()` tries to create a directory if it does not exist).

Additionally we can add nullcheck and probably throw some `IOException` with appropriate message.

If I understand correctly `IOException` here is now handled gracefully and does not cause request to be dropped.

**Closed** 2020-08-25 06:58 UTC
Labels: Pending PR, bug, incomplete

**Comment by CodeBreak524** [comment] 2020-08-25 10:38
Thanks, guys. Now it seems to be working without requests failing.

Special thanks to @koral-- for providing cases and scenarios to reproduce the problem
