### ISSUE TITLE
How do we avoid to intercept selective API ?

### ISSUE THREAD

**Issue by wahyupermadie** [ChuckerTeam/chucker#793] opened 2022-04-01 08:19 UTC
Hi, I want to ask is it possible for Chucker to set an exception for selective API Request to not show in the interceptor list ?
for example, I have an API request "api/v1/getuser" I want to this request not showing in chuker network request list

**Comment by cortinico** [comment] 2022-04-01 11:34
Nope that's not possible as of today. You can redact some fields however, not sure if that is helpful for you.

**Comment by wahyupermadie** [comment] 2022-04-03 17:45
thank you for the response @cortinico , yap I think it's not possible, my point is I want to avoid showing `restriction data` in Chucker View, for example, exclude endpoint that contains data of `lat lng, address, etc`

**Comment by cortinico** [comment] 2022-04-05 03:51
Nope that's not really possible as of today.

**Comment by MiSikora** [comment] 2022-04-18 11:43
Closing as a duplicate of #266.

**Closed by MiSikora** 2022-04-18 11:43 UTC
