### ISSUE TITLE
IllegalStateException: You can't access the transaction repository if you don't initialize it!

### ISSUE THREAD

**Issue by koral--** [ChuckerTeam/chucker#74] opened 2019-08-04 00:08 UTC
**Describe the bug**
```
    java.lang.IllegalStateException: You can't access the transaction repository if you don't initialize it!
        at com.chuckerteam.chucker.api.internal.data.repository.RepositoryProvider.transaction(RepositoryProvider.kt:16)
        at com.chuckerteam.chucker.api.internal.ui.transaction.TransactionListFragment.getDataSource(TransactionListFragment.java:136)
        at com.chuckerteam.chucker.api.internal.ui.transaction.TransactionListFragment.onAttach(TransactionListFragment.java:81)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1404)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:146)
```

**To Reproduce**
1. Invoke `context.startActivity(Chucker.getLaunchIntent(context, Chucker.SCREEN_HTTP))` where `context` is valid activity `Context`.
There is no HTTP(S) traffic logged before the invocation.

Sample project:
https://github.com/DroidsOnRoids/FoQA
Use `Chucker` Hyperion menu option to reproduce this issue.

**Expected behavior**
There should be no crash.

**Smartphone**
 - Device: does not matter but e.g. emulator
 - OS: does not matter but e.g. 5.0
 - Lib version: 3.0.0-alpha2

**Comment by cortinico** [comment] 2019-08-05 09:58
Thanks for the report @koral-- 
Apparently this is a duplicate of #68 and has already been fixed on `develop` (see PR number #71).

**Closed by cortinico** 2019-08-05 09:58 UTC
