### ISSUE TITLE
Response body is not shown when stream is not fully received

### ISSUE THREAD

**Issue by gmetal** [ChuckerTeam/chucker#370] opened 2020-07-02 11:10 UTC
## :writing_hand: Describe the bug
The TeeSource class that is used for wrapping around a response body Source and capture the response, requires the input stream to become exhausted (e.g. read() to return -1), in order to capture the response. However, it is possible that an entity reads the exact number of bytes to fully decode a resource, and then close the stream. In this case, the response is not captured (only the response headers are displayed).

This was working up until 3.1.2, and in version 3.2.0.

## :bomb: Steps to reproduce

I have created a sample app which demonstrates the problem. You can find it [here](https://github.com/gmetal/chucker-response-app). If you use the [retrofit-logansquare](https://github.com/mannodermaus/retrofit-logansquare) converter, no responses are shown. However, if you use either the kotlinx-serialization or moshi retrofit adapters, responses are properly shown.

## :wrench: Expected behavior

The responses bodies are included in the response.

## :camera: Screenshots
N/A

## :iphone: Tech info
 - Device: 
 - OS: 
 - Chucker version: 3.2.0

**Comment by MiSikora** [comment] 2020-07-02 14:19
This worked before because response was not streamed but fully read to the memory which was the cause of OOM issues. Displaying messages is rather tricky. Please see the discussion here - https://github.com/ChuckerTeam/chucker/pull/288.

**Comment by MiSikora** [comment] 2020-07-03 15:20
Ok, I've dug a little bit more into the issue and have more thoughts. `TeeSource` relies on upstream do be exhausted and the only available signal is `-1` byte count read. This allows us to decide what to do when the upstream is closed.

https://github.com/ChuckerTeam/chucker/blob/d689d454eacf4432d5c199db270b6cfb22a9a762/library/src/main/java/com/chuckerteam/chucker/internal/support/TeeSource.kt#L66-L73

One thing that could be changed is to do something like this instead.

```kotlin
try {
  callback.onSuccess(sideChannel)
} catch (e: IOExcepetion) {
  callSideChannelFailure(IOException("Upstream was not fully consumed", e))
} finally {
  sideChannel.delete()
}
```

Not sure if this is something that is wanted since Chucker might sometimes do an unnecessary amount of work for unexhausted responses but it would solve this issue. I can make a PR if @cortinico and @vbuberen find it ok. In my opinion, it should be fine since it is in the end a QA tool.

**Comment by cortinico** [comment] 2020-07-03 22:33
Thanks for reporting this @gmetal and thank you very much @MiSikora for already investigating.

> Not sure if this is something that is wanted since Chucker might sometimes do an unnecessary amount of work for unexhausted responses but it would solve this issue. I can make a PR if @cortinico and @vbuberen find it ok. In my opinion, it should be fine since it is in the end a QA tool.

Agree on what is stated here. I feel the current condition for calling `.onSuccess` is too strict. We should probably be fine calling it even if we haven't received an explicit `-1` while reading from upstream.

On the snippet you suggested @MiSikora 

```kotlin
try {
  callback.onSuccess(sideChannel)
} catch (e: IOExcepetion) {
```

I'm not sure I fully get what's your point here. Are we relying on the callback behavior to potentially raise a `IOExcepetion` here? If that's the case, I will just call `.onSuccess` during the `.close()` of the `TeeSource` and defer the handling of any potential `IOException` to the callback.

> Displaying partially consumed messages is rather tricky.

On a side note: we're also not showing a body if you hit `maxContentLength` (specified in the ctor). IIRC historically we used to show truncated response/request if `maxContentLength` was reached. So we might want to look into this as well while fixing this bug.

Anyway, please go ahead with a PR @MiSikora. Can I assign this issue to you?

**Comment by MiSikora** [comment] 2020-07-04 05:57
> I'm not sure I fully get what's your point here. Are we relying on the callback behavior to potentially raise a `IOExcepetion` here? If that's the case, I will just call `.onSuccess` during the `.close()` of the `TeeSource` and defer the handling of any potential `IOException` to the callback.

Kind of. We do not have any information whether the upstream was consumed or not so trying to parse it might fail with `IOException`. I think you're right and it makes more sense to defer handling it to the callback implementation.

> Anyway, please go ahead with a PR @MiSikora. Can I assign this issue to you?

Sure.

**Closed** 2020-07-09 21:30 UTC
Labels: Pending PR, bug

**Comment by gmetal** [comment] 2020-07-10 11:19
Thanks for the fix and the swift handling of the issue!
