### ISSUE TITLE
SQLiteException: no such table

### ISSUE THREAD

**Issue by deepakrathi** [ChuckerTeam/chucker#456] opened 2020-09-25 19:40 UTC
## :bomb: Steps to reproduce

1. Put the below code in your application class
2. and then redirect to some other activity
3. after redirection click the chucker log notification
4. app should crash here

**Code**
 val cache = context.cacheDir
                    val appDir = File(cache.parent)
                    if (appDir.exists()) {
                        val children = appDir.list()
                        for (s in children) {
                            if (s != "lib") {
                                deleteDir(File(appDir, s))
                            }
                        }
                    }

## :iphone: Tech info
 - Device: Google pixel 3A
 - OS: 11
 - Chucker version: 3.2.0

**Comment by MiSikora** [comment] 2020-09-27 16:56
Please update the ticket with correct use of sections and code formatting because right now it is a little bit hard to read. You can use #184 or any other bug ticket as a reference. Also, when reporting crashes please add a sample or a stack trace so we can investigate. Bugs that require more work from us to reproduce will naturally be done later.

As for the content there are two things.
1. Most likely, we should fix error handling on when handling queries to database. `LiveData` is in general poor abstraction because it does not have any error channels. Switching to `Flow` and handling `IOExceptions` should help.
2. I don't mean to tell you your business. However, IMHO you are being too aggressive with your cleanup. You're basically wiping everything except for `lib` directory. While it shows a bug in Chucker I would reconsider how you approach logout.

**Comment by vbuberen** [comment] 2021-09-22 14:11
Closing it considering no new info on this issue.

**Closed by vbuberen** 2021-09-22 14:11 UTC
Labels: bug

**Comment by koral--** [comment] 2021-09-22 14:51
I think it should be kept open due to the p 1. from Michał's post.
> we should fix error handling when handling queries to database

Unless this is already handled, tracked or explicitly decided to not change.
