### ISSUE TITLE
3.0.0-beta1 always shows "0" in notification

### ISSUE THREAD

**Issue by ColtonIdle** [ChuckerTeam/chucker#84] opened 2019-08-09 20:02 UTC
The beta shows

"AppName • 0 • Now"

vs the stable showing

"AppName • 1 • Now"

Looks like the count isn't incrementing in the beta vs stable.

**Comment by cortinico** [comment] 2019-08-09 20:06
@ColtonIdle I'm not sure I completely got your point, but apparently it works fine (latest master):
![photo5940438674225344623](https://user-images.githubusercontent.com/3001957/62806004-e26a1b00-baf1-11e9-8fe0-2e33129d63d8.jpg)

Can you provide more insights or a project that I can checkout and test?

**Comment by ColtonIdle** [comment] 2019-08-09 20:08
Looks like it's working for you. I don't think master has a release artifact available right?

What happens if you try with latest beta. Feel free to close for now if you want. I'll try the latest master when it's released.

**Comment by cortinico** [comment] 2019-08-09 20:19
> I don't think master has a release artifact available right?

There is no master branch 😅
You can anyway try the latest SNAPSHOT from the `develop` branch with:

```
dependencies {
  debugImplementation 'com.github.ChuckerTeam.Chucker:library:develop-SNAPSHOT'
  releaseImplementation 'com.github.ChuckerTeam.Chucker:library-no-op:develop-SNAPSHOT'
}
```

> Feel free to close for now if you want

I'm closing now but feel free to re-open if you manage to reproduce

**Closed by cortinico** 2019-08-09 20:19 UTC
Labels: invalid

**Comment by ColtonIdle** [comment] 2019-08-09 20:45
Oh. I thought there was a master branch because you said

> I'm not sure I completely got your point, but apparently it works fine (latest master)

I just tried this again, and it's still showing 0. Maybe it's because on the Q Beta 6?

I'll try on my api 28 emulator...

Nope. Shows 0 on the emulator.

<img width="214" alt="Screen Shot 2019-08-09 at 4 45 11 PM" src="https://user-images.githubusercontent.com/31751141/62808077-167b1700-bac5-11e9-9964-e26d7c4366a7.png">

**Comment by cortinico** [comment] 2019-08-09 21:00
Do you have other `Interceptors`?
Are you using any other proxy that might rewrite your requests (like Charles or similar)?

**Comment by ColtonIdle** [comment] 2019-08-09 21:03
I have a few things going on at the same time, like Flipper, etc. Let me remove them.

Just as a heads up though. If I migrate back down to the current stable, then the numbers show fine.

**Comment by cortinico** [comment] 2019-08-09 21:05
> I have a few things going on at the same time, like Flipper, etc. Let me remove them.

The best would be to have like a project that I can checkout where the issue is reproducible

**Comment by ColtonIdle** [comment] 2019-08-09 21:08
Removed flipper, stetho, etc. Same issue.

Tried downgrading again to make sure I wasn't going crazy. Sure enough, it works.

<img width="212" alt="Screen Shot 2019-08-09 at 5 07 43 PM" src="https://user-images.githubusercontent.com/31751141/62809186-39f39100-bac8-11e9-9d03-142ba8e2fe28.png">

**Comment by ColtonIdle** [comment] 2019-08-09 21:14
My project:

```
class MainActivity : AppCompatActivity() {

    lateinit var client: OkHttpClient
    lateinit var retrofit: Retrofit
    lateinit var service: MyService

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        client = OkHttpClient.Builder()
            .addInterceptor(ChuckInterceptor(this))
            .build()

        retrofit = Retrofit.Builder()
            .baseUrl("http://www.mocky.io/v2/")
            .client(client)
            .addConverterFactory(MoshiConverterFactory.create())
            .build()

        service = retrofit.create(MyService::class.java)
        button1.setOnClickListener { button1Clicked() }
    }

    fun button1Clicked() {
        val call = service.getPersonValid()
        call.enqueue(object : Callback<Person> {
            override fun onFailure(call: Call<Person>, t: Throwable) {
                Toast.makeText(this@MainActivity, "Fail", Toast.LENGTH_LONG).show()
            }
            override fun onResponse(call: Call<Person>, response: Response<Person>) {
                Toast.makeText(this@MainActivity, "Success", Toast.LENGTH_LONG).show()
            }
        })
    }
}
    interface MyService {
        @GET("5d4d9ebf3300003e3a33792e?mocky-delay=1000ms")
        fun getPersonValid(): Call<Person>
}
data class Person(
    val person: String = ""
)
```

If I use stable, the above works. If I change to SNAPSHOT (and also change ChuckInterceptor to ChuckerInterceptor) then it does **not** work.

**Comment by cortinico** [comment] 2019-08-10 12:17
Thanks for the code @ColtonIdle 
I was able to reproduce and here the potential fix: https://github.com/ChuckerTeam/chucker/pull/87
