### ISSUE TITLE
Chucker brokes my ui 

### ISSUE THREAD

**Issue by ismailtosun** [ChuckerTeam/chucker#864] opened 2022-08-05 06:10 UTC
When I added chucker in my project my buttons not visible.

My Button type is AppCompatButton

Any solitions for this ?

**Comment by vbuberen** [comment] 2022-08-05 07:18
Hello there. Without properly filled bug report template and some sample project which reproduces the issue we can't help you.

**Comment by vbuberen** [comment] 2022-09-09 06:53
Closing due to no further information.

**Closed by vbuberen** 2022-09-09 06:53 UTC
Labels: incomplete
