### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jhamin0511** [ChuckerTeam/chucker#215] opened 2020-01-29 03:31 UTC
## :loudspeaker: Describe the bug
This error was reported by Firebase Crashlytics. 

### :wrench: Expected behavior

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=23 srcPos=11 dst.length=23 dstPos=12 length=-1
       at java.lang.System.arraycopy(System.java)
       at com.android.internal.util.GrowingArrayUtils.insert(GrowingArrayUtils.java:129)
       at android.util.LongSparseArray.put(LongSparseArray.java:208)
       at com.chuckerteam.chucker.api.internal.support.NotificationHelper.addToBuffer(NotificationHelper.java:64)
       at com.chuckerteam.chucker.api.internal.support.NotificationHelper.show(NotificationHelper.java:82)
       at com.chuckerteam.chucker.api.ChuckerCollector.onResponseReceived$library_release(ChuckerCollector.java:66)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.java:138)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at kr.spendit.www.spendit.api.caller.HttpClientInterceptor.intercept(HttpClientInterceptor.java:44)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

## :iphone: Smartphone
 - Device: Galaxy S7
 - OS: 8.0.0
 - Lib version: 3.0.1

**Comment by cortinico** [comment] 2020-01-29 17:09
> This error was reported by Firebase Crashlytics.

Have you properly configured Chucker using the gradle configuration provided in the README?
Just want to make sure you haven't actually shipped the `library` version (instead of the `library-no-op`) to the user.

**Comment by jhamin0511** [comment] 2020-01-30 03:46
`implementation "com.github.ChuckerTeam.Chucker:library:3.0.1"`

We want to use Chucker with release builds.

Is `library-no-op` necessary?

**Comment by cortinico** [comment] 2020-01-30 07:45
> We want to use Chucker with release builds.
> Is library-no-op necessary?

In this case, no. It's not necessary.
Please note that your users will see the debug UI and will be able to inspect the network requests.

**Comment by cortinico** [comment] 2020-01-30 07:47
> Lib version: 3.0.1

Also can you please update to the latest version of the library `3.1.1`?

**Comment by jhamin0511** [comment] 2020-01-30 12:57
I will update to the latest version.

Thanks your answer.

**Comment by vbuberen** [comment] 2020-02-03 18:25
Hey @jhamin0511. 
Were you able to reproduce the issue on `3.1.1`?

**Comment by vbuberen** [comment] 2020-02-18 07:53
@jhamin0511 Do you have any additional info or more occurrences of this issue?

**Comment by vbuberen** [comment] 2020-04-05 07:43
Closing due to no feedback from the reporter

**Closed by vbuberen** 2020-04-05 07:43 UTC
Labels: incomplete
