### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by slott** [ChuckerTeam/chucker#720] opened 2021-11-11 10:17 UTC
## :writing_hand: Describe the bug
When running tests that make API calls the Chucker framework is triggered and it causes this error:

java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.

I know its bad to have tests that make API calls - but its an old test suite and we are working towards cleaning it up.

## :bomb: Steps to reproduce

Make a Robolectric test that makes an API call and the test will fail

## :wrench: Expected behavior

Test shouldn't fail

**Comment by MiSikora** [comment] 2021-11-11 13:56
Do you need to use Chucker in tests?

Regardless, can you provide a reproducible case? This shouldn't happen unless you use `InstantTaskExecutorRule` or some other mechanism that overrides architecture components executor.

**Comment by vbuberen** [comment] 2021-11-22 19:03
@slott Could you provide more info as requested in the previous comment?

**Comment by slott** [comment] 2021-11-22 20:42
Sorry for the delay - didn't get a notification until this second reply.

I'm executing the tests as Robolectric tests and everything is instant execution - so that sounds like we have found the culprit 😉

No way around that when running my tests.

**Comment by MiSikora** [comment] 2021-11-22 21:37
But do you need to apply `ChuckerInterceptor` in tests? Maybe you can provide an `OkHttpClient` that does not have `ChuckerInterceptor` added?

**Comment by MiSikora** [comment] 2021-11-23 06:22
Just in case you @slott have notification turned only for mentions, I'll ping you directly. Don't feel rushed, though. :)

**Comment by MiSikora** [comment] 2022-01-08 19:03
Since there is nothing for us to do, I'm closing this. The solution is not to use Chucker in tests.

**Closed by MiSikora** 2022-01-08 19:03 UTC
Labels: incomplete
