### ISSUE TITLE
Cannot open sample project

### ISSUE THREAD

**Issue by rakesh-sh2020** [ChuckerTeam/chucker#776] opened 2022-02-23 12:00 UTC
## :writing_hand: Describe the bug
I have cloned the repo locally and then tried to launch the sample app. I get an error saying:

**Task 'wrapper' not found in project ':sample'.**

## :bomb: Steps to reproduce

1. File/open sample/build.gradle file
2. See error Task 'wrapper' not found in project ':sample'.

## :wrench: Expected behavior

Launch the sample app on the connected device.

**Comment by cortinico** [comment] 2022-02-23 19:37
> 1. File/open sample/build.gradle file

I'm not sure I follow you here. You should open this project with IntelliJ or Android Studio. You can't just open the `sample/build.gradle` file nor the `sample/` folder

**Comment by rakesh-sh2020** [comment] 2022-02-24 09:26
I opened the repo in AS but its not an android application (at that level) since the app itself is in a sub directory of sample.

I usually run apps witin mono repos by opening the corresponding build.gradle file.

So how do I run the sample app?

**Comment by cortinico** [comment] 2022-02-25 15:01
> However, running the app leads to this error:

I think this is a bug introduced by a dependency bump and we should look into it. If someone wants to pick this up, this is a nice first task :)

**Comment by CompileConnected** [comment] 2022-03-25 11:13
Hi. how this bug reproduce?
because i don't get this problem

**Step running the sample project**

1. clone chucker and open the project
2. let it gradle sync
3. ./gradlew installGitHook
4. run play in emulator

**Tech used **
Android Studio bumbleBee 2021.1.1, built january 19 2022
Android Emulator SDK 24

**Comment by cortinico** [comment] 2022-03-25 12:16
I believe you might have to do some networking + kill & reopen the sample app a number of times.

**Comment by CompileConnected** [comment] 2022-03-25 12:59
So should I assume opening sample project and running step by step is already ok.
But while running the app, kill and reopen sample project multiple times might reproduce the bug?

Forgot to mention:
I tested in branch develop

**Comment by CompileConnected** [comment] 2022-03-25 18:47
**version**: chucker-3.5.2
**Android OS**: emulator
**Android Sdk**: 24

**version**: chucker-3.5.2
**Android OS**: emulator
**Android Sdk**: 32

**version**: chucker-4.0.0-SnapShot
**Android OS**: emulator
**Android Sdk**: 24

**version**: chucker-4.0.0-SnapShot
**Android OS**: emulator
**Android Sdk**: 32

But still unsuccessful to reproduce DiskReadViolation.

I try something else and I found this
**version**: chucker-4.0.0-SnapShot
**Android OS**: emulator
**Android Sdk**: 24
**Bug Founded**: LeakedClosableViolation

**Step to reproduce**:
1. Click Button "Do Http Activity" Fast and multiple times resulting the bug 

Other things that I try to reproduce LeakedClosableViolation in Android Sdk 32, using the same method but the bug is cannot be reproduce.


All test compiled in Android Studio 2021.1.1.

**Comment by cortinico** [comment] 2022-03-26 18:56
I've just tested this and I'm also not able to reproduce it. I'm closing it here for now. If we manage to have a reproducer, let's reopen this.

**Comment by cortinico** [comment] 2022-03-26 18:57
THanks for doing those tests @CompileConnected, really appreciate it 🙏 

> Bug Founded: LeakedClosableViolation

Could you open a separate issue for this?

**Closed by cortinico** 2022-03-26 18:56 UTC
Labels: help wanted

**Comment by CompileConnected** [comment] 2022-03-27 16:42
btw I try to reproduce the bug again that I make.
I think it's because a dirty build.
so in Emulator there's installed chucker 4 but I try to build chucker 3.
which resulting a weird behavior.

So I think I don't need open issue for this.

@cortinico happy to help
