### ISSUE TITLE
charset=UTF-8 is not showing

### ISSUE THREAD

**Issue by ilizma** [ChuckerTeam/chucker#331] opened 2020-04-25 17:43 UTC
## :writing_hand: Describe the bug
On the REQUEST tab, charset=UTF-8 is not showing on the header zone

## :bomb: Steps to reproduce
1. Make an API call with okHttp that adds the header charset=UTF-8 automatically
2. go to Chucker and click the tab REQUEST
3. See the header zone
4. charset=UTF-8 is not showing

## :wrench: Expected behavior
charset=UTF-8 is showing on the header zone

**Comment by cortinico** [comment] 2020-04-27 22:46
Thanks for reporting @ilizma 
I was able to reproduce locally. We actually just show the headers that OkHTTP passes us. Specifically we should append the Request `content-type` to the View in the Request tab.

Here a screenshot from Charles for the `/post` request:

![Screenshot 2020-04-28 at 00 31 33](https://user-images.githubusercontent.com/3001957/80428256-b7c32b00-88e9-11ea-99b3-60cd866b3db6.png)

**Comment by MiSikora** [comment] 2020-04-30 21:29
The problem is that, these headers are added as a part of `OkHttp` after application interceptors and before network interceptors do their work. The only thing that Chucker could do here is to not process the request that is being sent but rather one that is being returned by the interceptor.

Basically it would have to do something like this.

```kotlin
override fun intercept(chain: Chain): Response {
  // Some code…

  try {
    val response = chain.proceed(response)
    val responseForRequest = response.networkResponse() ?: response
    val requestToProcess = response.request()
    // Process the request
  } catch (e: IOException) {
    // Do whatever
  }

  // Some code…
}
```

But I don't think it is a good feature. Now, in case of an application interceptor, it mixes an application response with a network request. So it should always process a network response instead of an application response for the consistency. But at this point Chucker loses the flexibility of being used as an application interceptor. Another drawback is that requests are processed later or might not be processed at all in case of response failures.

I believe it should be up to the consumer. If they are interested in network traffic then use Chucker as a network interceptor.

**Comment by cortinico** [comment] 2020-05-11 16:57
> I believe it should be up to the consumer. If they are interested in network traffic then use Chucker as a network interceptor.

Agree on this point. I would avoid to do extra processing for exposing headers that are added by the library.

My suggestion was more related to:

> Specifically we should append the Request content-type to the View in the Request tab.

We actually store the request `content-type` in the DB but we never show it to the user.

**Comment by ArjanSM** [comment] 2022-12-13 00:26
Is this still up for grabs? 
Do we want to display the `content-type` in the overview tab or the Request tab?

**Comment by cortinico** [comment] 2022-12-13 14:58
> Is this still up for grabs? Do we want to display the `content-type` in the Overview tab or the Request tab?

Yup this is up for grab 👍

**Comment by vbuberen** [comment] 2022-12-13 22:04
I don't think there is anything to grab. We already discussed in issues like https://github.com/ChuckerTeam/chucker/issues/474 that `Content_type` appears or not depending in type of interceptor that user adds.

**Comment by cortinico** [comment] 2022-12-13 23:09
> I don't think there is anything to grab. We already discussed in issues like #474 that `Content-type` appears or not depending in type of interceptor that user adds.

Yup I misread my actual 2 year old response 🤦 We store `content-type` in the DB but it's pointless to manipulate the visualized header, and is up to the user to decide which interceptor to use.
I'm closing as there are no actionables

**Closed by cortinico** 2022-12-13 23:09 UTC
Labels: bug, help wanted
