### ISSUE TITLE
Large json responses result in bad user experience

### ISSUE THREAD

**Issue by ColtonIdle** [ChuckerTeam/chucker#82] opened 2019-08-09 19:33 UTC
Some of the backends I work with send really large amounts of data.

Here is a sample: https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.json

Moving from the request to response tab is slow, and trying to "Share as text" is also impossible. It'd be great to keep this on the roadmap for improvement.

Edit: Occurs in latest stable and beta

Edit 2: Maybe just show the first x amount of lines, but still provide a way to export or view the json as a file?

**Comment by cortinico** [comment] 2019-08-09 20:10
Part of this issue was addressed by @redwarp in #72 

> Edit 2: Maybe just show the first x amount of lines, but still provide a way to export or view the json as a file?

You can set the `maxContentLength` on the `ChuckerInterceptor` to truncate the body if needed (but still you won't be able to export or share the full body afterwards).

Curious to hear what others think about this

**Comment by ColtonIdle** [comment] 2019-08-09 20:15
Gotcha. I think after a certain size maybe 500k or something the text just gets treated as a file. Then in the response tab it can say "Response exceed x" with a button that opens the file in another file viewer. Also, the share as text would turn into a "Share as file" button?

**Comment by cortinico** [comment] 2019-08-09 20:21
Sounds more like as a feature-request.
Definitely valuable to implement :)

**Comment by redwarp** [comment] 2019-08-10 06:58
Actually, being able to open any response as a file with another viewer sounds like a great idea!

**Comment by kmayoral** [comment] 2019-10-29 20:43
Just tried out this library and it looks great, but the one thing keeping me from migrating over from Chuck is this issue where large json responses cause Chucker to hang and then eventually crash after you try and swipe from the Overview tab to either the Request or Response tab (probably when the data starts to get loaded into the Response tab).

Chuck is able to show these responses (even if there is no ability to search) so for now, I'll have to stay with Chuck. 

Looking forward to trying this library again in the future, it looks great!

**Comment by ColtonIdle** [comment] 2019-11-27 06:39
Just bumping this. Tried using Chucker on a new project and it's completely useless because of large json. It just ANRs. 😭

**Comment by cortinico** [comment] 2019-12-29 01:02
> Just bumping this. Tried using Chucker on a new project and it's completely useless because of large json. It just ANRs.

Thanks for bumping. Is this still happening? If yes, which version are you using? `3.0.1`?

**Comment by ColtonIdle** [comment] 2019-12-29 03:10
@cortinico yes this is still happening. I am using 3.0.1

**Comment by cortinico** [comment] 2020-01-02 16:44
Ok so after some investigation, turns out the issue is on the `TransactionPayloadFragment`. When dealing with big payloads, we hang the UI thread by setting the `text` of a `TextView` with a huge `String`:

https://github.com/ChuckerTeam/chucker/blob/32f711c23e84173dfc5fc9cbe57e6dc766ad2c44/library/src/main/java/com/chuckerteam/chucker/internal/ui/transaction/TransactionPayloadFragment.kt#L119

I do have a proposed fix for this, that unfortunately has a couple of drawbacks.

> Chuck is able to show these responses (even if there is no ability to search) 
> so for now, I'll have to stay with Chuck.

@kmayoral I've tried Chuck with the HTTP request that was suggested on top of this thread (https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.json) and the behavior is exactly the same.

**Closed** 2020-01-12 21:27 UTC
Labels: bug, help wanted, work-in-progress
