### ISSUE TITLE
About using latest version of anything

### ISSUE THREAD

**Issue by beigirad** [ChuckerTeam/chucker#770] opened 2022-02-12 09:06 UTC
Usually third-party libraries are depending on minimum version of anything. But unfortunately this project is using the latest version of anything. Fragment, Material and so on. And I as a developer must be consider for transitive all* libraries version.

I should decide which version of above libraries is suit for my project. Not Chucker forces me to using for example Material 1.4.0 :/ What's the relation between Chucker and Material?

I think it's a bad decision. And I can't upgrade Chucker because of this transitive versions of irrelevant dependencies.

**Comment by cortinico** [comment] 2022-02-15 09:37
> What's the relation between Chucker and Material?

All the Chucker UI is built using the Material Design Components library. So it's actually used.

> I think it's a bad decision.

What would be your suggestion instead?

**Comment by vbuberen** [comment] 2022-02-15 13:11
> This behavior respects other developers to manage their app dependencies version.
> 
> I'm looking for reason of upgrading MDC and I found [6fe1f344](https://github.com/ChuckerTeam/chucker/commit/6fe1f34423e57ef5ad7657b1e3834b8a57cc5fd1). So it was unnecessary. Also In my opinion @dependabot is useful for application projects, not libraries that is used in other apps. Its unnecessary and harmful for Chucker.

It is pretty valid from one side and I would agree with you here, but I also think it is double sided coin. Having tools moving forward with dependencies versions is good for encouraging users update their projects instead of sticking with some very old version for a very long time saying `We have no time to update as we need to ship features` and, eventually, leading to even worse situation where the project has a big gap in versions for some dependencies with breaking changes, making the update process of such dependencies even more painful and time consuming.

I would agree that we, probably, shouldn't run for the latest version for Chucker, but sticking with min working version - isn't an option from my point of view.

**Comment by ebraminio** [comment] 2022-02-15 21:34
Dear Chucker developers, first of all thanks for providing this awesome piece of work and providing it freely to the community :)

I think the discussion is unnecessary heated and that hasn't happened in purpose so let's forget about all that and continue calmly :)

So the initial problem here has been a client of the library has challenged due to transitive upgrades they got from this library. From what I've seen elsewhere, libraries, in order to maximize their ease of use try to keep their required version of their dependencies to lowest versions and that is common practice at least from what I've learnt in C libraries of Linux distributions and from the amount I've seen also in Android libraries as this for example [this](https://github.com/square/leakcanary/blob/bef49a7/gradle/libs.versions.toml#L16) and [this](https://github.com/square/leakcanary/blob/bef49a7/gradle/libs.versions.toml#L36-L39) also suggest (and those "Exposed transitively, avoid increasing" comments there)

For sure for a volunteer project like this awesome project, it is too much of expectation to change an established process overnight but I like to suggest to the maintainers of this project whether if is possible to revise the policy of updating dependencies of the libraries to not upgrade based on when the new release is available but when the release is actually needed. For sure this shouldn't become obstacle for you to use new needed features so whenever there is a needed upgrade, the policy shouldn't stop you from upgrading to new versions but it is for ease of use for some of the clients.

Thank you for consideration :)

**Comment by MiSikora** [comment] 2022-02-16 22:49
I agree that libraries should use the lowest compatible versions of dependencies possible, and I think this is the only user-friendly approach. In the ideal world, we would drop any dependencies other than`OkHttp` Unfortunately, we have limited resources, so we more or less have to rely on external dependencies.

Having said that, I personally would be up for lowering versions of most of our dependencies.

**Comment by cortinico** [comment] 2022-02-17 00:06
In general, agree with the points raised here. We should try to be more mindful when bumping deps. On the other hand however, Dependabot is alleviating a lot of the burden when bumping versions.

One question: if you're having a problem as Chucker imposes MDC 1.4.0, why don't you disable the transitive dependency resolution from Chucker? 

```
dependencies {
  debugImplementation("com.github.chuckerteam.chucker:library:3.5.2") {
	transitive = false
  }
}
```
That allows you to fully manage the dependency version Chucker is exposing.

Or alternatively, why don't you set a strict MDC version to the one you wish to use?

```
dependencies {
  implementation("com.google.android.material:material:1.3.0") {
    version {
      strictly '1.3.0'
    }
  }
}
```

Which version of MDC are you suggesting we downgrade to also?

It's hard to make a pick for all the libraries on which would be the minimum we want to support. We could totally downgrade Kotlin to 1.0 and release it, but would it be worth?

We could argue that MDC is not as crucial for Chucker as Kotlin or OkHTTP. We introduced it deciding that it was a valid addition to the library as the ecosystem was moving in that direction.

> eventually I stop using Chucker or do not upgrading Chucker!

Also you're complaining about a change that hasn't been released yet. I don't understand your argument about "not upgrading". Are you using a `-SNAPSHOT` version by any chance? If so, that's at your own risk essentially ([it's also written in the README](https://github.com/ChuckerTeam/chucker#snapshots-)).

**Comment by vbuberen** [comment] 2022-02-17 09:11
> Which version of MDC are you suggesting we downgrade to also?
> 
> It's hard to make a pick for all the libraries on which would be the minimum we want to support. We could totally downgrade Kotlin to 1.0 and release it, but would it be worth?

As an option here I see setting Dependabot schedule to work really rare, like once per 3 months of so. I believe that if we see some dependency has some important/critical update, which we definitely need, we will update it on our own. And Dependabot will be just catching up with things we don't notice or forget to update.

**Comment by vbuberen** [comment] 2022-02-17 09:13
Potentially, we can make it even ~6 months and it still won't be that rare. For things like `lifecycle-ktx` we rarely have a need to jump right into it. As to Material - I would love us to slowly more to Material 3 styles as well.

**Comment by cortinico** [comment] 2022-03-26 18:43
> Also you're complaining about a change that hasn't been released yet. I don't understand your argument about "not upgrading". Are you using a `-SNAPSHOT` version by any chance? If so, that's at your own risk essentially ([it's also written in the README](https://github.com/ChuckerTeam/chucker#snapshots-)).

Closing as I supsect this was the root cause. Feel free to re-open if it was not the case.

**Closed by cortinico** 2022-03-26 18:43 UTC
Labels: discussion
