### ISSUE TITLE
Support for `ktor` networking library using in `android` and `kmp` projects.

### ISSUE THREAD

**Issue by devrath** [ChuckerTeam/chucker#1240] opened 2024-07-06 11:13 UTC
## :warning: Is your feature request related to a problem? Please describe
*  I use `ktor` for my project. I taught of using this library but there is no support for this in the library
*  `Ktor` is needed since `KMP` we use it

## :bulb: Describe the solution you'd like
Support for `ktor` networking library

## :bar_chart: Describe alternatives you've considered
The only alternative I can see is using `okhttp`

## :raising_hand: Do you want to develop this feature yourself?
- [ ] Yes
- [x] No

**Comment by cortinico** [comment] 2024-07-08 09:22
Duplicate of:
- https://github.com/ChuckerTeam/chucker/issues/927
- https://github.com/ChuckerTeam/chucker/issues/1040
- https://github.com/ChuckerTeam/chucker/issues/952

**Closed by cortinico** 2024-07-08 09:22 UTC

**Comment by akardas16** [comment] 2024-11-26 19:46
it is possible to use Okhttp client for just debug in ktor 
```
  val httpClient = if (BuildConfig.DEBUG) {
                val okhttpEngine = OkHttp.create {
                    addInterceptor(ChuckerInterceptor(context))
                }
                HttpClient(okhttpEngine){
                    install(ContentNegotiation) {
                        json(Json {
                            prettyPrint = true
                            isLenient = true
                            ignoreUnknownKeys = true
                        }) // Example: Register JSON content transformation
                        // Add more transformations as needed for other content types

                        Gson()

                    }

                    install(HttpTimeout){//5 Minute
                        requestTimeoutMillis = 300000
                        connectTimeoutMillis = 300000
                        socketTimeoutMillis = 300000
                    }
                }
            }else{
                HttpClient(Android){
                    install(ContentNegotiation) {
                        json(Json {
                            prettyPrint = true
                            isLenient = true
                            ignoreUnknownKeys = true
                        }) // Example: Register JSON content transformation
                        // Add more transformations as needed for other content types

                        Gson()

                    }

                    install(HttpTimeout){//5 Minute
                        requestTimeoutMillis = 300000
                        connectTimeoutMillis = 300000
                        socketTimeoutMillis = 300000
                    }
                }
            }
```
