### ISSUE TITLE
StrictMode violation - android.os.strictmode.DiskWriteViolation

### ISSUE THREAD

**Issue by KiraFleming** [ChuckerTeam/chucker#782] opened 2022-03-09 00:58 UTC
## :writing_hand: Describe the bug
```
D/StrictMode: StrictMode policy violation; ~duration=618 ms: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1552)
        at libcore.io.BlockGuardOs.remove(BlockGuardOs.java:340)
        at libcore.io.ForwardingOs.remove(ForwardingOs.java:185)
        at android.app.ActivityThread$AndroidOs.remove(ActivityThread.java:7616)
        at java.io.UnixFileSystem.delete(UnixFileSystem.java:331)
        at java.io.File.delete(File.java:1037)
        at com.chuckerteam.chucker.internal.data.room.ChuckerDatabase$Companion.create(ChuckerDatabase.kt:22)
        at com.chuckerteam.chucker.internal.data.repository.RepositoryProvider.initialize(RepositoryProvider.kt:34)
        at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:32)
        at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:23)
```

## :bomb: Steps to reproduce
Init Chucker with detectAll() as the StrictMode policy

## :iphone: Tech info
 - Device: Nokia G10
 - OS: 11
 - Chucker version: 3.5.2

**Comment by cortinico** [comment] 2022-03-10 10:26
I believe this is a duplicate of #737 and got already fixed on #750

**Closed** 2022-10-04 16:43 UTC
