### ISSUE TITLE
LeakCanary reports a leak

### ISSUE THREAD

**Issue by niltsiar** [ChuckerTeam/chucker#102] opened 2019-08-23 08:42 UTC
**Describe the bug**
LeakCanary reports a leak of `MainActivity`. I've been able to reproduce it in my own application and in the sample app. It doesn't matter if there are captured network requests or not.

**To Reproduce**
Steps to reproduce the behavior using the sample app:
1. Go to 'LAUNCH CHUCKER DIRECTLY'
2. Click on 'Back Button'
3. See error either in logcat or in LeakCanary UI

**Screenshots**
LeakCanary result in logcat:

    ┬
    ├─ android.app.Activity$1
    │    Leaking: UNKNOWN
    │    Anonymous subclass of android.app.IRequestFinishCallback$Stub
    │    GC Root: Global variable in native code
    │    ↓ Activity$1.this$0
    │                 ~~~~~~
    ╰→ com.chuckerteam.chucker.api.internal.ui.MainActivity
    ​     Leaking: YES (Activity#mDestroyed is true and ObjectWatcher was watching this)
    ​     key = 3d3901ea-a7b9-47fa-ba5a-566d1ede5924
    ​     watchDurationMillis = 5185
    ​     retainedDurationMillis = 178
    , retainedHeapByteSize=165749)], libraryLeaks=[])

**Smartphone**
 - Device: Pixel 3XL
 - OS: Android Q Beta6
 - Lib version: 3.0.1 and `develop` branch

**Additional context**
I haven't being able to reproduce it in other android versions. I suppose this is happening due to Android Q but I don't know if it's a false positive from LeakCanary or not. I've attached the memory dump from LeakCanary

[2019-08-23_10-25-44_445.hprof.zip](https://github.com/ChuckerTeam/chucker/files/3533581/2019-08-23_10-25-44_445.hprof.zip)

**Comment by cortinico** [comment] 2019-08-23 21:59
Thanks for the report @niltsiar 
I'm leaving this opened and free to pickup if someone wants to investigate more what's going on.

**Comment by adtyx** [comment] 2019-08-27 04:11
@niltsiar is this reproducible? I was unable to reproduce this on Android Q beta 7.
@cortinico my guess is activity was destroyed while viewpager was still in transaction. this is a bleak possibilty.

**Comment by niltsiar** [comment] 2019-08-27 08:08
@adtyx it's reproducible every time using Android Q Beta 6, with my own projects and with `Chucker` sample. As far as I know there is no such beta 7, at least for Pixel devices.

I've made a test just leaving `setContentView` as the only thing the `MainActivity` does and also removing the `ViewPager` from the XML. The leak still appears.

**Comment by cortinico** [comment] 2019-08-27 13:42
> @niltsiar is this reproducible? I was unable to reproduce this on Android Q beta 7.

@adtyx I saw it happening from time to time on a Pixel3, latest Android Q beta. I haven't really investigated on this but I'll be happy to assign this issue to a volunteer :)

**Comment by niltsiar** [comment] 2019-09-04 08:22
I've tested it again with the new final version of Android 10. I've also updated my local copy of `Chucker` sample to use the latest `LeakCanary-2.0-beta-3` and the issue is still happening.

**Comment by mrenouf** [comment] 2019-09-09 20:32
It is a framework issue:
https://issuetracker.google.com/issues/139738913

**Comment by caiodev** [comment] 2019-12-09 09:41
On the last update of Android 10 on OnePlus 7 this leak is not being reported anymore. So there's a great chance it's been fixed

**Comment by aoben10** [comment] 2020-01-07 02:22
I'm still seeing this issue.

```
Known leak pattern: instance field android.app.Activity$1#this$0
Description: Android Q added a new android.app.IRequestFinishCallback$Stub class. android.app.Activity creates an implementation of that interface as an anonymous subclass. That anonymous subclass has a reference to the activity. Another process is keeping the android.app.IRequestFinishCallback$Stub reference alive long after Activity.onDestroyed() has been called, causing the activity to leak.
338984 bytes retained
┬
├─ android.app.Activity$1
│    Leaking: UNKNOWN
│    Anonymous subclass of android.app.IRequestFinishCallback$Stub
│    GC Root: Global variable in native code
│    ↓ Activity$1.this$0
│                 ~~~~~~
╰→ com.chuckerteam.chucker.api.internal.ui.MainActivity
​     Leaking: YES (Activity#mDestroyed is true and ObjectWatcher was watching this)
​     key = 274de02a-4a5e-4767-8367-3db4c6b397c1
​     watchDurationMillis = 5124
​     retainedDurationMillis = 120


METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Google
LeakCanary version: 2.0
App process name: com.myapp
Analysis duration: 5785 ms
```

**Comment by cortinico** [comment] 2020-01-07 09:13
@aoben10 thanks for the LeakCanary report. From which version of Chucker is this related? Can I ask you to try using the latest SNAPSHOT from `develop` and confirm that is happening again?

**Comment by vbuberen** [comment] 2020-01-07 13:58
It seems to be not Chucker issue: https://github.com/square/leakcanary/issues/1594

**Comment by aoben10** [comment] 2020-01-07 14:04
Thanks for letting me know @vbuberen

**Comment by vbuberen** [comment] 2020-01-07 18:29
Closing as an issue not related to the library.

**Closed by vbuberen** 2020-01-07 18:29 UTC
Labels: help wanted
